CREATE USER ORAC_SYS_USER IDENTIFIED BY p@ssWord DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE APPLICATION_USER;

ALTER USER ORAC_SYS_USER PASSWORD EXPIRE;

GRANT CREATE SYNONYM TO ORAC_SYS_USER;

GRANT CREATE SESSION TO ORAC_SYS_USER;

CREATE ROLE ORAC_SYS_USER_ROLE;

GRANT SELECT ON DB_NM.TBL_NM_01 TO ORAC_SYS_USER_ROLE;

GRANT ORAC_SYS_USER_ROLE TO ORAC_SYS_USER;

CREATE SYNONYM ORAC_SYS_USER.TBL_NM_01 FOR DB_NM.TBL_NM_01;
CREATE SYNONYM ORAC_SYS_USER.TBL_NM_02 FOR DB_NM.TBL_NM_02;
CREATE SYNONYM ORAC_SYS_USER.TBL_NM_03 FOR DB_NM.TBL_NM_03;

REVOKE SELECT ON DB_NM.TBL_NM_01 FROM ORAC_SYS_USER_ROLE;

DROP SYNONYM ORAC_SYS_USER.TBL_NM_01;
